"""Initial schema - no auth

Revision ID: 15d7dce272e8
Revises: 8dbd0ab8cddd
Create Date: 2026-01-27 19:00:58.094178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15d7dce272e8'
down_revision: Union[str, None] = '8dbd0ab8cddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sessions_id', table_name='sessions')
    op.drop_index('ix_sessions_token', table_name='sessions')
    op.drop_index('ix_sessions_user_id', table_name='sessions')
    op.drop_index('ix_sessions_vet_id', table_name='sessions')
    op.drop_table('sessions')
    op.drop_column('users', 'password_hash')
    op.drop_column('vets', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vets', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('vet_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('token', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='sessions_user_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vet_id'], ['vets.id'], name='sessions_vet_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sessions_pkey')
    )
    op.create_index('ix_sessions_vet_id', 'sessions', ['vet_id'], unique=False)
    op.create_index('ix_sessions_user_id', 'sessions', ['user_id'], unique=False)
    op.create_index('ix_sessions_token', 'sessions', ['token'], unique=True)
    op.create_index('ix_sessions_id', 'sessions', ['id'], unique=False)
    # ### end Alembic commands ###
