"""PR feedback changes

Revision ID: 776d28b62e9b
Revises: 9f8e74a6857f
Create Date: 2026-01-30 19:36:41.078247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '776d28b62e9b'
down_revision: Union[str, None] = '9f8e74a6857f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add scheduled_at as nullable first
    op.add_column('appointments', sa.Column('scheduled_at', sa.DateTime(), nullable=True))

    # Migrate data: combine date and time into scheduled_at
    op.execute("""
        UPDATE appointments
        SET scheduled_at = date + time
        WHERE date IS NOT NULL AND time IS NOT NULL
    """)

    # Now make scheduled_at non-nullable
    op.alter_column('appointments', 'scheduled_at', nullable=False)

    op.drop_index('ix_appointments_date', table_name='appointments')
    op.create_index(op.f('ix_appointments_scheduled_at'), 'appointments', ['scheduled_at'], unique=False)
    op.drop_column('appointments', 'time')
    op.drop_column('appointments', 'date')
    op.add_column('blog_posts', sa.Column('author_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_blog_posts_author_id'), 'blog_posts', ['author_id'], unique=False)
    op.create_foreign_key(None, 'blog_posts', 'vets', ['author_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('notifications_vet_id_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'vets', ['vet_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key('notifications_vet_id_fkey', 'notifications', 'vets', ['vet_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'blog_posts', type_='foreignkey')
    op.drop_index(op.f('ix_blog_posts_author_id'), table_name='blog_posts')
    op.drop_column('blog_posts', 'author_id')

    # Add back date and time columns
    op.add_column('appointments', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=True))

    # Migrate data back: extract date and time from scheduled_at
    op.execute("""
        UPDATE appointments
        SET date = scheduled_at::date, time = scheduled_at::time
        WHERE scheduled_at IS NOT NULL
    """)

    # Make date and time non-nullable
    op.alter_column('appointments', 'date', nullable=False)
    op.alter_column('appointments', 'time', nullable=False)

    op.drop_index(op.f('ix_appointments_scheduled_at'), table_name='appointments')
    op.create_index('ix_appointments_date', 'appointments', ['date'], unique=False)
    op.drop_column('appointments', 'scheduled_at')
    # ### end Alembic commands ###
