"""Add vet client management tables

Revision ID: 9996ec0e40ef
Revises: e5f6g7h8i9j0
Create Date: 2026-02-19 10:40:30.419393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '9996ec0e40ef'
down_revision: Union[str, None] = 'e5f6g7h8i9j0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vet_clients',
    sa.Column('vet_id', sa.UUID(), nullable=False),
    sa.Column('pet_owner_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invite_token', sa.String(length=64), nullable=True),
    sa.Column('invite_expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pet_owner_id'], ['pet_owners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vet_id'], ['vets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vet_id', 'email', name='uq_vet_client_email')
    )
    op.create_index(op.f('ix_vet_clients_id'), 'vet_clients', ['id'], unique=False)
    op.create_index(op.f('ix_vet_clients_invite_token'), 'vet_clients', ['invite_token'], unique=True)
    op.create_index(op.f('ix_vet_clients_pet_owner_id'), 'vet_clients', ['pet_owner_id'], unique=False)
    op.create_index(op.f('ix_vet_clients_vet_id'), 'vet_clients', ['vet_id'], unique=False)
    op.create_table('vet_client_pets',
    sa.Column('vet_client_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', postgresql.ENUM('DOG', 'CAT', 'OTHER', name='pettype', create_type=False), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('gender', postgresql.ENUM('MALE', 'FEMALE', name='gender', create_type=False), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vet_client_id'], ['vet_clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vet_client_pets_id'), 'vet_client_pets', ['id'], unique=False)
    op.create_index(op.f('ix_vet_client_pets_vet_client_id'), 'vet_client_pets', ['vet_client_id'], unique=False)
    op.drop_index('ix_users_email', table_name='pet_owners')
    op.drop_index('ix_users_id', table_name='pet_owners')
    op.create_index(op.f('ix_pet_owners_email'), 'pet_owners', ['email'], unique=True)
    op.create_index(op.f('ix_pet_owners_id'), 'pet_owners', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pet_owners_id'), table_name='pet_owners')
    op.drop_index(op.f('ix_pet_owners_email'), table_name='pet_owners')
    op.create_index('ix_users_id', 'pet_owners', ['id'], unique=False)
    op.create_index('ix_users_email', 'pet_owners', ['email'], unique=True)
    op.drop_index(op.f('ix_vet_client_pets_vet_client_id'), table_name='vet_client_pets')
    op.drop_index(op.f('ix_vet_client_pets_id'), table_name='vet_client_pets')
    op.drop_table('vet_client_pets')
    op.drop_index(op.f('ix_vet_clients_vet_id'), table_name='vet_clients')
    op.drop_index(op.f('ix_vet_clients_pet_owner_id'), table_name='vet_clients')
    op.drop_index(op.f('ix_vet_clients_invite_token'), table_name='vet_clients')
    op.drop_index(op.f('ix_vet_clients_id'), table_name='vet_clients')
    op.drop_table('vet_clients')
    # ### end Alembic commands ###
