"""Add email_verified to vets

Revision ID: a1e93efa02ad
Revises: d42bf6ee1848
Create Date: 2026-03-14 20:41:04.486354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1e93efa02ad'
down_revision: Union[str, None] = 'd42bf6ee1848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reminders', 'is_sent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('reminders', 'is_dismissed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('service_types', 'duration_minutes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('service_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.add_column('vets', sa.Column('email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vets', 'email_verified')
    op.alter_column('service_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('service_types', 'duration_minutes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('30'),
               existing_nullable=False)
    op.alter_column('reminders', 'is_dismissed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('reminders', 'is_sent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    # ### end Alembic commands ###
